[mdzk]
authors = ["distromari"]
ignore = []
language = "en"
multilingual = false
src = "notes"
title = "Mari's braincells"
backlinks-header = "Backlinks"

[build]
create-missing = false
build-dir = "book"